### ISSUE TITLE
Consider renaming the project

### ISSUE THREAD

**Issue by snicoll** [domix/jade4j-spring-boot-starter#13]
As described [in the documentation](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-custom-starter-naming) we prefer that 3rd party starters do no start with `spring-boot`. 

Could you please rename the starter so that we can include it [in our list](https://github.com/spring-projects/spring-boot/tree/master/spring-boot-starters)?

Thanks!

**Comment by domix** [comment]
Sure! will do that!

**Comment by odin88** [comment]
Any updates ?

**Comment by domix** [comment]
Sorry, I'll do it in the following 3 weeks

**Comment by snicoll** [comment]
Any update?

**Comment by domix** [comment]
Hi @snicoll, sorry for the delay, the project is renamed now.

**Comment by snicoll** [comment]
@domix it looks like the `build.gradle` needs to be updated to reflect the new name. It is important that the artifact you publish is compliant with our naming recommendation.

**Comment by domix** [comment]
@snicoll just applied the changes to `build.gradle`

**Comment by snicoll** [comment]
Thanks but we're not there yet. If I checkout this project and I build it, It generates the following artifacts:

```
-rw-r--r--  1 snicoll  staff    32K Jul 12 08:28 spring-boot-starter-jade4j-0.3.3-javadoc.jar
-rw-r--r--  1 snicoll  staff   5.3K Jul 12 08:28 spring-boot-starter-jade4j-0.3.3-sources.jar
-rw-r--r--  1 snicoll  staff   8.6K Jul 12 08:28 spring-boot-starter-jade4j-0.3.3.jar
```

Ultimately, a release of this project will still violate the naming convention.

**Comment by domix** [comment]
Now seems to be fixed, thanks @snicoll!
